providers:
  openai_gpt4:
    provider_name: openai
    model: gpt-4
  openai_gpt35:
    provider_name: openai
    model: gpt-3.5
  anthropic:
    model: claude-v2
  gemini:
    model: gemini-pro
  ollama:
    model: llama2
    endpoint: "http://localhost:11434/api"
default_provider: openai_gpt4